name: adult-mlflow
channels: [conda-forge, defaults]
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow==2.19.0
      - scikit-learn>=1.3.0
      - numpy
      - pandas
      - joblib
      - matplotlib
